const USER_ACTIONS = {
    LOGIN: 'LOGIN',
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT', 
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
}

export default USER_ACTIONS;