const USER_ACTIONS = {
    LOGIN: 'LOGIN',
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT', 
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    GET_MAGAZINES_START: 'GET_MAGAZINES_START',
    GET_MAGAZINES_SUCCESS: 'GET_MAGAZINES_SUCCESS',
    GET_MAGAZINES_FAILED: 'GET_MAGAZINES_FAILED'
}

export default USER_ACTIONS;